TODO: compare radix-tree (but need newer lts or something)
c.f. https://github.com/sergv/radix-tree/pull/1

$ stack build

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for radix-tree-1.0.0.0:
    template-haskell-2.16.0.0 from stack configuration does not match >=2.17 && <3  (latest matching version is 2.19.0.0)
needed due to countwordsHS-0.1.0.0 -> radix-tree-1.0.0.0